insert into user values(1, sysdate(), 'John Doe')
insert into user values(2, sysdate(), 'Jane Doe')
insert into user values(3, sysdate(), 'Roe Smith')
insert into user values(4, sysdate(), 'Wade Wilson')
insert into user values(5, sysdate(), 'Filadora Figg')